### ISSUE TITLE
Update to 1.0.3

### ISSUE THREAD

**Issue by FlyinPancake** [kuflierl/Flatpak-org.fritzing.Fritzing#13]
1.0.3 just released. <https://fritzing.org/releases/1-0-3> 
Can you update the artifact?

**Comment by kuflierl** [comment]
Thanks for letting me know, will probably be done till tomorrow.

**Comment by kuflierl** [comment]
@FlyinPancake i have created a per-release [pv1.0.3b_1](https://github.com/kuflierl/Flatpak-org.fritzing.Fritzing/releases/tag/pv1.0.3b_1). Would you mind testing the pre-release and letting me know if everything works before i make it a full release?

**Comment by FlyinPancake** [comment]
I'll be able to check it tomorrow morning CET time

**Comment by FlyinPancake** [comment]
Tested and seems working just fine :+1:
